
api-port:               8051
www-port:               84

db-host:                localhost
db-port:                27017
db-name-primary:        sundowner_primary_dev
db-name-analytics:      sundowner_analytics_dev

cache-host:             localhost
cache-port:             6379
cache-db:               1
cache-key-auth:         auth

queue-host:             localhost
queue-port:             5557

fb-app-id:              215833641927561
fb-app-secret:          274af04abdb6490a4186a23a75f5d80d

analytics:
    port:               83
    fb-app-id:          627843653945574
    fb-app-secret:      f504f2908d81726781a8ed4dd480ccac

