
api-port:               8000
www-port:               8001

db-host:                localhost
db-port:                27017
db-name-primary:        sundowner_primary_dev
db-name-analytics:      sundowner_analytics_dev

cache-host:             localhost
cache-port:             6379
cache-db:               1

queue-host:             127.0.0.1
queue-port:             5557

fb-app-id:              215833641927561
fb-app-secret:          274af04abdb6490a4186a23a75f5d80d

analytics:
    port:               8002
    fb-app-id:          627843653945574
    fb-app-secret:      f504f2908d81726781a8ed4dd480ccac

score-weights:
    vote:               0.8
    day_offset:         0.3
    week_offset:        0.1
    friend:             2.0
    location:           1.5

